env: PongNoFrameskip-v4
eps_start: 1.0
eps_end: 0.02
eps_last_frame: 150000
sync_rate: 1000
gamma: 0.99
learning_rate: 0.0001
batch_size: 32
replay_size: 100000
warm_start_size: 10000
avg_reward_len: 100
min_episode_reward: -21
seed: 123
batches_per_epoch: 1000
n_steps: 1
